<UI>:
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "Hello kivyMD"
            font_style: 'Subtitle1'
            halign: 'center'
            #color: "#C4FF33"
            #theme_text_color: "Custom"
            text_color: 0, 0, 1, 1
        MDIcon:
            icon: "help"
            pos_hint: {"center_x":.5, "center_y": .5}
            color: "red"

